// Skylite build: bundle the TS app with esbuild, cache-bust the entry, and emit
// a self-contained static `dist/` (arecipe pattern — no framework, no router).
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, rmSync, mkdirSync, cpSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const root = dirname(fileURLToPath(import.meta.url));
const dist = join(root, 'dist');

/** Build stamp: package version + short git SHA (falls back gracefully). */
function computeVersion() {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  let sha = 'nogit';
  try {
    sha = execFileSync('git', ['rev-parse', '--short=7', 'HEAD'], { cwd: root })
      .toString()
      .trim();
  } catch {
    // No git (e.g. tarball build) — leave the sentinel.
  }
  return `v1 ${pkg.version}+${sha}`;
}

const version = computeVersion();

// Each destination page: its root HTML template, TS entry, and the token the
// template uses for the hashed script src (arecipe page-per-destination shape).
const PAGES = [
  { html: 'index.html', entry: 'src/main.ts', token: '%MAIN_JS%' },
  { html: 'sponsor.html', entry: 'src/sponsor.ts', token: '%SPONSOR_JS%' },
  { html: 'audit.html', entry: 'src/audit.ts', token: '%AUDIT_JS%' },
  { html: 'saves.html', entry: 'src/saves/page.ts', token: '%SAVES_JS%' },
  { html: 'post.html', entry: 'src/post/page.ts', token: '%POST_JS%' },
  { html: 'mysky.html', entry: 'src/mysky/page.ts', token: '%MYSKY_JS%' },
  { html: 'help.html', entry: 'src/help.ts', token: '%HELP_JS%' },
];

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });

// Bundle the app; hashed filenames let the service worker (Phase 3) cache-bust.
const result = await esbuild.build({
  entryPoints: PAGES.map((p) => join(root, p.entry)),
  bundle: true,
  format: 'esm',
  target: 'es2022',
  minify: true,
  sourcemap: true,
  entryNames: 'assets/[name]-[hash]',
  outdir: dist,
  metafile: true,
  define: {
    __SKYLITE_VERSION__: JSON.stringify(version),
  },
});

// Find an emitted (hashed) entry JS for a given source entry point.
function entryHref(srcEntry) {
  const out = Object.keys(result.metafile.outputs).find(
    (o) => o.endsWith('.js') && result.metafile.outputs[o].entryPoint === srcEntry,
  );
  if (!out) throw new Error(`build: could not locate bundled entry for ${srcEntry}`);
  return '/' + out.replace(/^dist\//, '');
}
const pageHrefs = Object.fromEntries(PAGES.map((p) => [p.entry, entryHref(p.entry)]));

// Static assets copied verbatim into dist. (Note: assets/brand/source/ is NEVER
// listed here — the multi-MB source renders must not ship; see tests/e2e/
// brand-bundle.spec.ts.)
for (const asset of ['manifest.webmanifest', 'CNAME', 'icons', '.nojekyll', 'LICENSE', 'oauth']) {
  const from = join(root, asset);
  if (existsSync(from)) {
    cpSync(from, join(dist, asset), { recursive: true });
  }
}

// The served stylesheet is tokens.css (brand tokens, the only place raw hex
// lives) concatenated with styles.css (components), so tokens resolve first in
// a single request with no per-page <link> juggling.
writeFileSync(
  join(dist, 'styles.css'),
  `${readFileSync(join(root, 'tokens.css'), 'utf8')}\n${readFileSync(join(root, 'styles.css'), 'utf8')}`,
);

// Render the HTML pages from their root templates, injecting version + entries.
const stylesHref = `/styles.css?v=${encodeURIComponent(version)}`;
function renderPage(templateName, replacements) {
  const template = readFileSync(join(root, templateName), 'utf8');
  let html = template.replaceAll('%VERSION%', version).replaceAll('%STYLES%', stylesHref);
  for (const [token, value] of Object.entries(replacements)) html = html.replaceAll(token, value);
  writeFileSync(join(dist, templateName), html);
}
for (const p of PAGES) renderPage(p.html, { [p.token]: pageHrefs[p.entry] });

// Generate the service worker with a precache manifest keyed to this exact build
// (IDEAS.md §4: skipWaiting + clients.claim + a visible version stamp, so a
// child always runs the build we shipped — a stale SW can strand safety patches).
const precache = [
  '/',
  ...PAGES.map((p) => `/${p.html}`),
  '/manifest.webmanifest',
  stylesHref,
  ...PAGES.map((p) => pageHrefs[p.entry]),
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/apple-touch-icon-180.png',
];
const sw = `// GENERATED by build.mjs — do not edit. Build ${version}.
const CACHE = 'skylite-${version.replace(/[^\w.+-]/g, '_')}';
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const res = await fetch(request);
  if (res && res.ok) {
    const cache = await caches.open(CACHE);
    cache.put(request, res.clone());
  }
  return res;
}

async function networkFirst(request) {
  try {
    const res = await fetch(request);
    if (res && res.ok) {
      const cache = await caches.open(CACHE);
      cache.put(request, res.clone());
    }
    return res;
  } catch (err) {
    const cached = await caches.match(request);
    if (cached) return cached;
    throw err;
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  // App shell HTML: network-first so a shipped update is picked up next open,
  // falling back to the cached shell when offline.
  if (request.mode === 'navigate' || (request.headers.get('accept') || '').includes('text/html')) {
    event.respondWith(networkFirst(request));
    return;
  }
  // Bluesky blob images: cache-first so the garden's pictures survive offline.
  if (url.hostname.endsWith('cdn.bsky.app')) {
    event.respondWith(cacheFirst(request));
    return;
  }
  // Feed / config reads: network-first with cache fallback (offline garden).
  if (url.pathname.startsWith('/xrpc/')) {
    event.respondWith(networkFirst(request));
    return;
  }
  // Content-hashed same-origin assets: cache-first.
  if (url.origin === self.location.origin) {
    event.respondWith(cacheFirst(request));
  }
});
`;
writeFileSync(join(dist, 'sw.js'), sw);

console.log(`built ${version} -> dist/  (${PAGES.length} pages, sw + precache ${precache.length})`);
