// GENERATED by build.mjs — do not edit. Build v1 0.1.0+48893cd.
const CACHE = 'bluebird-v1_0.1.0+48893cd';
const PRECACHE = ["./","index.html","patrol.html","audit.html","locker.html","post.html","my-mountain.html","trailmap.html","help.html","ski-school.html","manifest.webmanifest","styles.css?v=v1%200.1.0%2B48893cd","assets/main-OYV3XYRB.js","assets/sponsor-GC72APC2.js","assets/audit-UG6ZRGPG.js","assets/page-KUW2XR7M.js","assets/page-NFRFLUOG.js","assets/page-34JOQBXC.js","assets/page-YAWASEPZ.js","assets/help-PEPAN57Y.js","assets/ski-school-ZJKYMGHP.js","icons/icon-192.png","icons/icon-512.png","icons/apple-touch-icon-180.png"];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const res = await fetch(request);
  if (res && res.ok) {
    const cache = await caches.open(CACHE);
    cache.put(request, res.clone());
  }
  return res;
}

async function networkFirst(request) {
  try {
    const res = await fetch(request);
    if (res && res.ok) {
      const cache = await caches.open(CACHE);
      cache.put(request, res.clone());
    }
    return res;
  } catch (err) {
    const cached = await caches.match(request);
    if (cached) return cached;
    throw err;
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  // App shell HTML: network-first so a shipped update is picked up next open,
  // falling back to the cached shell when offline.
  if (request.mode === 'navigate' || (request.headers.get('accept') || '').includes('text/html')) {
    event.respondWith(networkFirst(request));
    return;
  }
  // Bluesky blob images: cache-first so the garden's pictures survive offline.
  if (url.hostname.endsWith('cdn.bsky.app')) {
    event.respondWith(cacheFirst(request));
    return;
  }
  // Feed / config reads: network-first with cache fallback (offline garden).
  if (url.pathname.startsWith('/xrpc/')) {
    event.respondWith(networkFirst(request));
    return;
  }
  // Content-hashed same-origin assets: cache-first.
  if (url.origin === self.location.origin) {
    event.respondWith(cacheFirst(request));
  }
});
